// <auto-generated />
using System;
using BlazorProduct.Api.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorProduct.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240814073022_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlazorProduct.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateTimeCaptured")
                        .HasColumnType("datetime2");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PartNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e15bd8dc-5f05-422d-8fdd-b7bd7866265b"),
                            DateTimeCaptured = new DateTime(2024, 8, 14, 7, 30, 21, 822, DateTimeKind.Utc).AddTicks(497),
                            Model = "MX1000",
                            Name = "Wireless Mouse",
                            PartNumber = "WMX1000-123",
                            Price = 29.99m,
                            Quantity = 50
                        },
                        new
                        {
                            Id = new Guid("3955f33e-af31-4547-877e-615484de9cd1"),
                            DateTimeCaptured = new DateTime(2024, 8, 14, 7, 30, 21, 822, DateTimeKind.Utc).AddTicks(638),
                            Model = "MK450",
                            Name = "Mechanical Keyboard",
                            PartNumber = "MK450-456",
                            Price = 89.99m,
                            Quantity = 30
                        },
                        new
                        {
                            Id = new Guid("c0c58c14-fe69-4b60-b739-47c3fd7580f7"),
                            DateTimeCaptured = new DateTime(2024, 8, 14, 7, 30, 21, 822, DateTimeKind.Utc).AddTicks(702),
                            Model = "GH200",
                            Name = "Gaming Headset",
                            PartNumber = "GH200-789",
                            Price = 59.99m,
                            Quantity = 25
                        },
                        new
                        {
                            Id = new Guid("d9ee4d98-d4ac-410f-ad88-22cfae7227d1"),
                            DateTimeCaptured = new DateTime(2024, 8, 14, 7, 30, 21, 822, DateTimeKind.Utc).AddTicks(766),
                            Model = "UHD27",
                            Name = "4K Monitor",
                            PartNumber = "UHD27-101",
                            Price = 299.99m,
                            Quantity = 10
                        },
                        new
                        {
                            Id = new Guid("87934a87-b6c2-4a41-845a-8d1b653acd04"),
                            DateTimeCaptured = new DateTime(2024, 8, 14, 7, 30, 21, 822, DateTimeKind.Utc).AddTicks(826),
                            Model = "XH1TB",
                            Name = "External Hard Drive",
                            PartNumber = "XH1TB-102",
                            Price = 59.99m,
                            Quantity = 75
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
